### PR TITLE
Issue 1808 add sys parameters from expression

### LINKED ISSUE #1808: System parameteres in expressions are not added when pasting components
**Describe the bug**
When pasting a component with a parameter mapped to a system parameter, the system parameter is added to the system if it does not already exist. However, if the system parameter is used in a NumHop expression (e.g. "-x"), it is not added.

**To Reproduce**
*If the bug can be reproduce, please give the steps taken to reproduce the behavior:*
1. Add component A
2. Add system paramter X
3. Set a parameter in A to -X
4. Copy component A
5. Create a new model
6. Paste component A
7. It is not possible to simulate the model, since "X" is not available

**Expected behavior**
X should be added to the target model.

### PR DESCRIPTION
**Pull request by peterNordin**
Use numhop expression to extract variable names

**Note!** Update of submodule numhop needed, also renamed libNumHop and IndexingCSVParser to lower case. May need "git submodule update --init" or "git submodule sync"

Resolves #1808

### CODE REVIEW

File: HopsanGUI/GUIObjects/GUIContainerObject.cpp [hunk 1]
```diff
@@ -1486,30 +1486,45 @@ void ContainerObject::copySelected(CopyStack *xmlStack)
     appendCoordinateTag(*copyRoot, center.x(), center.y());
 
     // Copy components
+    const auto thisSystemsParameterNames = getParameterNames();
```
Comment (robbr48) [inline HopsanGUI/GUIObjects/GUIContainerObject.cpp]: I'm not sure if I like this variable name. Can't it just be called "systemParameterNames"?

Comment (peterNordin) [reply HopsanGUI/GUIObjects/GUIContainerObject.cpp]: When I tried to understand my old dusty code to fix this the name confused me. Since this code deals with figuring out what system parameters are used. This new name is more clear and may reduce confusion the next time someone tries to understand that code. But yes the name is silly
