### PR TITLE
Issue 1960 plo v2 import export bugs

### LINKED ISSUE #1960: PLOLookuptable not working
PLOLookuptable not working

**To Reproduce**
*If the bug can be reproduce, please give the steps taken to reproduce the behavior:*
1. Export data from some model using  >> sapl temp.plo x
2. Create a new model, containing the component PLOlookuptable
3. Try using the newly saved plo file...
4. The program will either: Be unable to open the file, Crash, or complain on the perfectly sorted "Time" vector used as input.

Expected behaviour: plo-files should work out-of-the box with this component.

**Screenshots, Model or Data files**
*If applicable, add screenshots, models or data files, that display or cause the bug.*

**Hopsan version (please complete the following information):**
*Version information is shown in the message widget when HopsanGUI is started*
 - OS: Windows 10
 - Version: HopsanCore 64-bit, Version: 2.13.0.20191126.1813
                       HopsanGUI 64-bit, Version: 2.13.0.20191126.1813
 - Build: official.

**Additional information**
There might be an issue with how many lines the parser discards or the version number exported from hopsan.

### PR DESCRIPTION
**Pull request by peterNordin**
- Fix bugs in PLO v2 import and export
- Adds tests for PLO v1 and v2
- Adds missing PLO lookuptable "data as embedded text" functionality
- Prevent truncation of data when you add "large embedded text data"

Resolves #1960

### CODE REVIEW

**Comment by peterNordin** [comment]
@robbr48 Maybe we should merge this back to the 2.14.x branch (together with your fix of the data logger), since 2.15 make take some time until its done. What do you think ?

File: UnitTests/HopsanCoreTests/ComponentUtilitiesTest/tst_componentutilitiestesttest.cpp [hunk 1]
```diff
@@ -538,6 +538,83 @@ private Q_SLOTS:
...
+        QTest::addColumn< QString >("indexDataName");
+        QTest::addColumn< QString >("outputDataName");
+        QTest::addColumn< bool >("expectParseOK");
+        QTest::addColumn< int >("expectedInIndex");
+        QTest::addColumn< int >("expectedOutIndex");
+        QTest::addColumn< double >("expectedLastValue");
+
+        QString ploData1 = R"(
+          'VERSION'
+          1
```
Comment (robbr48) [inline UnitTests/HopsanCoreTests/ComponentUtilitiesTest/tst_componentutilitiestesttest.cpp:579]: Raw string literals only works for C++11 and above (but I guess you noticed  this already).
